---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "website-redirects"
  annotations:
    openshift.io/display-name: "Decommissioned Website Redirects"
    description: "Provides website redirects for old, decommissioned OpenShift websites"
    iconClass: "icon-shadowman"
    template.openshift.io/provider-display-name: "Red Hat, Inc."
message: "The following service(s) have been created in your project: ${NAME}."
labels:
  template: "website-redirects"
objects:
  - kind: "Service"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "${NAME}"
      annotations:
        description: "Exposes and load balances the frontend application pods"
      labels:
        app: "${NAME}"
    spec:
      ports:
        - name: "8080-tcp"
          port: 8080
          protocol: "TCP"
          targetPort: 8080
      selector:
        name: "${NAME}"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "openshift-org"
      labels:
        app: "${NAME}"
    spec:
      host: "openshift.org"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "developers-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "developers.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "forums-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "forums.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "enterprise-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "enterprise.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "install-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "install.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "origin-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "origin.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "hub-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "hub.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "marketplace-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "marketplace.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "ideas-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "ideas.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"
        caCertificate: "${CA_CERTIFICATE}"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "openshift-redhat-com"
      labels:
        app: "${NAME}"
    spec:
      host: "openshift.redhat.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "www-rhcloud-com"
      labels:
        app: "${NAME}"
    spec:
      host: "www.rhcloud.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "www-openshift-org"
      labels:
        app: "${NAME}"
    spec:
      host: "www.openshift.org"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "docs-openshift-org"
      labels:
        app: "${NAME}"
    spec:
      host: "docs.openshift.org"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "okd-io"
      labels:
        app: "${NAME}"
    spec:
      host: "okd.io"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "projectquay-io"
      labels:
        app: "${NAME}"
    spec:
      host: "projectquay.io"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "osdworkshop-io"
      labels:
        app: "${NAME}"
    spec:
      host: "osdworkshop.io"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "try-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "try.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "blog-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "blog.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "Route"
    apiVersion: "v1"
    metadata:
      annotations:
        kubernetes.io/tls-acme: "true"
      name: "blog-openshift-com"
      labels:
        app: "${NAME}"
    spec:
      host: "account.openshift.com"
      to:
        kind: "Service"
        name: "${NAME}"
        weight: 1
      port:
        targetPort: "8080-tcp"

  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "${NAME}"
      annotations:
        description: "Keeps track of changes in the ${NAME} application image"
      labels:
        app: "${NAME}"

  - kind: "ImageStream"
    apiVersion: "v1"
    metadata:
      name: "httpd-24-rhel7"
      annotations:
        description: "Upstream httpd 2.4 s2i image"
      labels:
        app: "${NAME}"
    spec:
      lookupPolicy:
        local: false
      tags:
      - annotations: null
        from:
          kind: "DockerImage"
          name: "registry.access.redhat.com/rhscl/httpd-24-rhel7"
        generation: 0
        importPolicy:
          scheduled: true
        name: "latest"
        referencePolicy:
          type: "Source"

  - kind: "BuildConfig"
    apiVersion: "v1"
    metadata:
      name: "${NAME}"
      annotations:
        description: "Defines how to perform the build for ${NAME} before deployment"
      labels:
        app: "${NAME}"
    spec:
      nodeSelector:
      source:
        type: "Git"
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${SOURCE_REPOSITORY_REF}"
        contextDir: "${CONTEXT_DIR}"
        sourceSecret:
          name: "${SOURCE_CLONE_SECRET}"
      strategy:
        type: "Source"
        sourceStrategy:
          from:
            kind: "ImageStreamTag"
            name: "httpd-24-rhel7:latest"
      output:
        to:
          kind: "ImageStreamTag"
          name: "${NAME}:latest"
      triggers:
        - type: "ImageChange"
        - type: "ConfigChange"
        - type: "GitHub"
          github:
            secret: "${GITHUB_WEBHOOK_SECRET}"

  - kind: "DeploymentConfig"
    apiVersion: "v1"
    metadata:
      name: "${NAME}"
      annotations:
        description: "Defines how to deploy the httpd deployment"
      labels:
        app: "${NAME}"
    spec:
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: "Rolling"
      triggers:
        - type: "ImageChange"
          imageChangeParams:
            automatic: true
            containerNames:
              - "${NAME}"
            from:
              kind: "ImageStreamTag"
              name: "${NAME}:latest"
        - type: "ConfigChange"
      replicas: 1
      test: false
      selector:
        name: "${NAME}"
      template:
        metadata:
          name: "${NAME}"
          labels:
            name: "${NAME}"
            app: "${NAME}"
        spec:
          containers:
            - name: "${NAME}"
              ports:
                - containerPort: 8080
              resources:
                requests:
                  cpu: "${CPU_REQUEST}"
                  memory: "${MEMORY_REQUEST}"
                limits:
                  cpu: "${CPU_LIMIT}"
                  memory: "${MEMORY_LIMIT}"

  - kind: "HorizontalPodAutoscaler"
    apiVersion: "autoscaling/v1"
    metadata:
      name: "${NAME}"
      labels:
        app: "${NAME}"
    spec:
      scaleTargetRef:
        kind: DeploymentConfig
        name: "${NAME}"
        apiVersion: "v1"
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 75

parameters:
  - name: "NAME"
    displayName: "Application name"
    description: "The name assigned to all of the application components defined in this template."
    required: true
    value: "redirects"

  - name: "SOURCE_REPOSITORY_URL"
    displayName: "Git Repository URL"
    description: "The URL of the repository with your application source code."
    required: true
    value: "git@github.com:openshift-cs/redirects.git"

  - name: "SOURCE_REPOSITORY_REF"
    displayName: "Git Reference"
    description: "Set this to a branch name, tag or other ref of your repository if you are not using the default branch."

  - name: "CONTEXT_DIR"
    displayName: "Context Directory"
    description: "Set this to the relative path to your project if it is not in the root of your repository."

  - name: "SOURCE_CLONE_SECRET"
    displayName: "Source Clone Secret Name"
    description: "The name of your source clone secret, used to provide the builder with access to your private GitHub repo."
    required: true
    value: "github-redirects"

  - name: "CPU_REQUEST"
    displayName: "CPU Request"
    description: "Requested amount of CPU the httpd container will use."
    required: true
    value: "50m"

  - name: "CPU_LIMIT"
    displayName: "CPU Limit"
    description: "Maximum amount of CPU the httpd container can use."
    required: true
    value: "500m"

  - name: "MEMORY_REQUEST"
    displayName: "Memory Request"
    description: "Requested amount of memory the httpd container will use."
    required: true
    value: "100Mi"

  - name: "MEMORY_LIMIT"
    displayName: "Memory Limit"
    description: "Maximum amount of memory the httpd container can use."
    required: true
    value: "512Mi"

  - name: "GITHUB_WEBHOOK_SECRET"
    displayName: "GitHub Webhook Secret"
    description: "A secret string used to configure the GitHub webhook."
    generate: "expression"
    from: "[a-zA-Z0-9]{40}"
